// Code generated by goctl. DO NOT EDIT.
// Source: mdHistory.proto

package futurehistickservice

import (
	"context"

	"github.com/rz1998/invest-md-uju/rpc/mdHistory/types/mdHistoryUju"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BusinessReqMessage        = mdHistoryUju.BusinessReqMessage
	BusinessRespMessage       = mdHistoryUju.BusinessRespMessage
	Data                      = mdHistoryUju.Data
	DynamicContent            = mdHistoryUju.DynamicContent
	Header                    = mdHistoryUju.Header
	LoginReqMessage           = mdHistoryUju.LoginReqMessage
	LoginRespMessage          = mdHistoryUju.LoginRespMessage
	NettyMessage              = mdHistoryUju.NettyMessage
	OnOrder                   = mdHistoryUju.OnOrder
	OnTrade                   = mdHistoryUju.OnTrade
	Request                   = mdHistoryUju.Request
	Response                  = mdHistoryUju.Response
	StaticContent             = mdHistoryUju.StaticContent
	UJU_SSEL2_BondStatic      = mdHistoryUju.UJU_SSEL2_BondStatic
	UJU_SSEL2_BondTick        = mdHistoryUju.UJU_SSEL2_BondTick
	UJU_SSEL2_Order           = mdHistoryUju.UJU_SSEL2_Order
	UJU_SSEL2_STATIC          = mdHistoryUju.UJU_SSEL2_STATIC
	UJU_SSEL2_Transaction     = mdHistoryUju.UJU_SSEL2_Transaction
	UJU_SZSEL2_Order          = mdHistoryUju.UJU_SZSEL2_Order
	UJU_SZSEL2_STATIC         = mdHistoryUju.UJU_SZSEL2_STATIC
	UJU_SZSEL2_Tick           = mdHistoryUju.UJU_SZSEL2_Tick
	UJU_SZSEL2_Transaction    = mdHistoryUju.UJU_SZSEL2_Transaction
	UJU_TDF_BBQBID_DATA       = mdHistoryUju.UJU_TDF_BBQBID_DATA
	UJU_TDF_BBQTRANSACTION    = mdHistoryUju.UJU_TDF_BBQTRANSACTION
	UJU_TDF_BROKER_QUEUE      = mdHistoryUju.UJU_TDF_BROKER_QUEUE
	UJU_TDF_FUTURE_DATA       = mdHistoryUju.UJU_TDF_FUTURE_DATA
	UJU_TDF_INDEX_DATA        = mdHistoryUju.UJU_TDF_INDEX_DATA
	UJU_TDF_MARKET_CLOSE_DATA = mdHistoryUju.UJU_TDF_MARKET_CLOSE_DATA
	UJU_TDF_MARKET_DATA       = mdHistoryUju.UJU_TDF_MARKET_DATA
	UJU_TDF_ORDER             = mdHistoryUju.UJU_TDF_ORDER
	UJU_TDF_ORDER_QUEUE       = mdHistoryUju.UJU_TDF_ORDER_QUEUE
	UJU_TDF_TRANSACTION       = mdHistoryUju.UJU_TDF_TRANSACTION

	FutureHisTickService interface {
		// 查询期货期权历史行情
		QueryFutureHisTick(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		// 查询股票历史行情
		QueryStockHisTick(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultFutureHisTickService struct {
		cli zrpc.Client
	}
)

func NewFutureHisTickService(cli zrpc.Client) FutureHisTickService {
	return &defaultFutureHisTickService{
		cli: cli,
	}
}

// 查询期货期权历史行情
func (m *defaultFutureHisTickService) QueryFutureHisTick(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := mdHistoryUju.NewFutureHisTickServiceClient(m.cli.Conn())
	return client.QueryFutureHisTick(ctx, in, opts...)
}

// 查询股票历史行情
func (m *defaultFutureHisTickService) QueryStockHisTick(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := mdHistoryUju.NewFutureHisTickServiceClient(m.cli.Conn())
	return client.QueryStockHisTick(ctx, in, opts...)
}
